project:
  type: website
  output-dir: docs

website:
  favicon: img/harmonize.ico
  title: "Innovalab"
  twitter-card: 
    image: "img/DJI_0860_13febrero.JPG"
    creator: "@antony_barja"
    site: "@antony_barja"
  open-graph:
    description: description
  navbar:
    logo: https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/harmonize.svg
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap
      - href: methodology.qmd
        text: Methodology
      - href: https://healthinnovation.github.io/harmonize-dashboard/
        text: Data audit
      - href: table.qmd
        text: Dataset  
    right:
      - icon: github
        href: https://github.com/healthinnovation/Harmonize-Project
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual
