project:
  type: website
  output-dir: docs

website:
  favicon: img/harmonize.ico
  title: "Innovalab"
  twitter-card: 
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
    creator: "@antony_barja"
    site: "@antony_barja"
  open-graph:
    description: "Harmonize is a collaboration project with Colombia, Brazil, Dominican Republic and Peru, led by the Barcelona Supercomputing Center and funded by Wellcome Trust, that aims to develop a digital infrastructure to harmonize climate, health and drone data for every country in the consortium."
    image: "https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/twitter-card.png"
  navbar:
    logo: https://raw.githubusercontent.com/healthinnovation/Harmonize-Project/main/img/harmonize.svg
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap
      - href: methodology.qmd
        text: Methodology
      - href: https://healthinnovation.github.io/harmonize-dashboard/
        text: Data audit
      - href: https://innovalab-upch.shinyapps.io/droneapp/
        text: Orthomosaics 
      - href: https://innovalab-upch.shinyapps.io/hmz-meteoroapp/
        text: Meteorological stations
    right:
      - icon: github
        href: https://github.com/healthinnovation/harmonize
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual