project:
  type: website
  output-dir: docs

website:
  title: "Innovalab"
  open-graph: true
  navbar:
    logo: img/Harmonize.svg
    favicon: img/background.png
    left:
      - href: index.qmd
        text: Home
      - href: webmap.qmd
        text: Webmap
      - href: methodology.qmd
        text: Methodology
      - href: https://healthinnovation.github.io/harmonize-dashboard/
        text: Data audit
    right:
      - icon: github
        href: https://github.com/healthinnovation/Harmonize-Project
      - icon: twitter
        href: https://twitter.com/innovalab_imt
  
format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true

editor: visual
