# https://github.com/pommevilla/friendly-dollop/blob/master/.github/workflows/quarto-render.yml
name: Render and deploy Quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install R pacakges"
        uses: r-lib/actions/setup-r@v2
      - name: dependencies
        run: |
          Rscript -e "install.packages(c('tidyverse','leaflet','leaflet.extras','sf','viridis','reactable','leaflegend','purrr','cluster','pheatmap','factoextra','FactoMineR','yardstick'))"

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-render@main

      - name: "Deploy to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
